language: node_js
node_js:
  - "14"
  - "12"
  - "10"
script:
  - npm test
os:
  - linux
  - osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      pip install --user cpplint;
    else
      pip install cpplint;
    fi
notifications:
  email: false

